### ISSUE TITLE
[字符编码兼容问题]py2与py3在解析yaml函数的时候py3正常，py2异常

### ISSUE THREAD

**Issue by RockFeng0** [RockFeng0/rtsf#3]
```
# democase.yaml
- case: 
...
...
    verify:
        - ${Call_Func_A(参数1)}

# run below
# py3 is ok,   but py2 is not
from rtsf.p_executer import TestRunner
from httpdriver.driver import HttpDriver
runner = TestRunner(runner = HttpDriver).run('democase.yaml')
html_report = runner.gen_html_report()
```

**Comment by RockFeng0** [comment]
在 rtsf中， eval_content_with_bind_actions函数，可以在py3中编码统一是str可以正常解析中文，在py2的时候函数转换为了unicode，该函数无法解析。

**解决方法是，统一使用参数化**
```
# democase.yaml
- case:
...
...
    glob_var:
        var1: 参数1
    verify:
        - ${Call_Func_A($var1)}
```
